version: 2.1

jobs:
  analyze:
    executor:
      name: docker/machine
      image: ubuntu-2204:2022.04.2
#    docker:
#      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          command: docker-compose up -d
      - maven/with_cache:
          steps:
            - run:
                command: mvn package pact:publish -Dquarkus.container-image.build=false
      - maven/with_cache:
          steps:
            - run:
                command: mvn package sonar:sonar -DskipTests -Dquarkus.container-image.build=false

executors:
  machine:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@2.2.0

workflows:
  maven_test:
    jobs:
#      - maven/test:
#          executor: machine
#          command: 'verify'
      - analyze:
          context: SonarCloud