version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:19.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn package sonar:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:19.0'
  machine:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@1.4.0

workflows:
  maven_test:
    jobs:
#      - maven/test:
#          executor: jdk
      - maven/test:
          executor: machine
          command: '-X verify'
      - build:
          context: SonarCloud